name: CI

on:
  pull_request:
    paths:
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '.eslintrc.cjs'
      - '.prettierrc.json'
      - '.github/workflows/ci-typescript.yml'
  push:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - '.eslintrc.cjs'
      - '.prettierrc.json'
      - '.github/workflows/ci-typescript.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.24'
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test
      - name: Run lint
        run: bun run lint
      - name: Check formatting
        run: bun run format:check
